# Generated by Django 3.1.3 on 2024-04-20 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
